language: node_js

image: docker

services:
  - docker

before_install:
  - docker info
  - sudo apt-get update
  - sudo apt-get install bash grep
  - if [ -z $VERSION ]; then VERSION=$(echo $TRAVIS_COMMIT_MESSAGE | grep -oP "(?<=##)(.*)(?=##)"); fi

stages:
  - name: build-master
    if: branch = master
  - name: build-dev
    if: branch = dev

jobs:
  include:
    - stage: build-master
      name: build docker
      script:
        - docker version
        - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
        - docker build -t $DOCKER_HUB_SLUG:$VERSION .
        - docker push $DOCKER_HUB_SLUG:$VERSION
    - stage: build-dev
      name: build docker
      script:
        - docker version
        - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
        - docker build -t $DOCKER_HUB_SLUG:$VERSION-dev .
        - docker push $DOCKER_HUB_SLUG:$VERSION-dev