language: node_js

image: docker

services:
  - docker

before_install:
  - docker info
  - sudo apt-get update
  - sudo apt-get install bash grep
  - if [ -z $VERSION ]; then VERSION=$(echo $TRAVIS_COMMIT_MESSAGE | grep -oP "(?<=##)(.*)(?=##)"); fi
  - echo $VERSION

# if: $TRAVIS_BRANCH = "master"
#   # - echo $TRAVIS_BRANCH
# script:
#   - docker version
#   - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
#   - docker build -t $DOCKER_HUB_SLUG:$VERSION .
#   - docker push $DOCKER_HUB_SLUG:$VERSION

# if: $TRAVIS_BRANCH = "dev"
#   # - echo $TRAVIS_BRANCH
script:
  # branch = ?
  - echo $TRAVIS_BRANCH
  - if [ $TRAVIS_BRANCH == dev ]; then echo "WORKS" && echo "STILL WORKS"; fi
  - docker version
  - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
  - docker build -t $DOCKER_HUB_SLUG:$VERSION-dev .
  - docker push $DOCKER_HUB_SLUG:$VERSION-dev

# script:
#   - docker version
#   - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
#   - docker build -t $DOCKER_HUB_SLUG:$VERSION .
#   - docker push $DOCKER_HUB_SLUG:$VERSION