sudo: required

language: node_js

image: docker:latest

services:
  - docker:dind

before_install:
  - docker info
  - sudo apk update && apk upgrade && apk add bash grep
  - if [ -z $VERSION ]; then VERSION=$(echo $CI_COMMIT_MESSAGE | grep -oP "(?<=##)(.*)(?=##)"); fi

build-master:
  stage: build
  script:
    - docker version
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$VERSION .
    - docker push $CI_REGISTRY_IMAGE:$VERSION
    - bundle exec rake
  only:
    - master
    - master-schedule
  
build-dev:
  stage: build
  script:
    - docker version
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$VERSION-dev .
    - docker push $CI_REGISTRY_IMAGE:$VERSION-dev
  only:
    - dev
  except:
    - schedules
