language: node_js

image: docker

services:
  # docker:dind doesn't exist for travis ci
  - docker
  - mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

dist: trusty

# name: Log in to registry
# uses: actions/docker/login@master
# env:
#   DOCKER_REGISTRY_URL: docker.pkg.github.com
#   DOCKER_USERNAME: ${{ github.actor }}
#   DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
# if: github.event_name == 'push'
  

before_install:
  - docker info
  # - cat /etc/os-release
  # test mysql
  - composer self-update
  - composer clear-cache
  # test mysql
  - sudo apt update
  # ---- command failing ----
  # - sudo apt upgrade
  # ---- command failing ----
  - sudo apt install bash grep
  # ---- command failing ----
  # - if [ -z $VERSION ]; then VERSION=$(echo $TRAVIS_COMMIT_MESSAGE | grep -oP "(?<=##)(.*)(?=##)"); fi
  # ---- command failing ----
  - sudo apt list --upgradable
  - sudo apt upgrade

build-master:
  stage: build
  script:
    - docker version
    
    # -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY WRONG
    # - docker login -u DOCKER_USERNAME -p $DOCKER_PASSWORD $CI_REGISTRY
    - docker login -u DOCKER_USERNAME -p $DOCKER_PASSWORD
    # - docker build -t $CI_REGISTRY_IMAGE:$VERSION .
    # - docker push $CI_REGISTRY_IMAGE:$VERSION
    # - bundle exec rake
  only:
    - master
    - master-schedule
  
build-dev:
  stage: build
  script:
    - docker version
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$VERSION-dev .
    - docker push $CI_REGISTRY_IMAGE:$VERSION-dev
  only:
    - dev
  except:
    - schedules
