
language: node_js

node_js:
  - 10.1

image: docker

services:
  - docker

before_install:
  - docker info
  - sudo apt-get nodejs
  - sudo npm i -g npm@6.1.0
  - sudo apt-get update
  - sudo apt-get install bash grep
  - if [ -z $VERSION ]; then VERSION=$(echo $TRAVIS_COMMIT_MESSAGE | grep -oP "(?<=##)(.*)(?=##)"); fi

stages:
  - name: test
  - name: zip-checksum
    if: branch = master

jobs:
  include:
    - stage: test
      name: test deployment
      script:
        - cd scripts/ci
        - sudo bash ci-tester.sh
    - stage: zip-checksum
      name: create zip-checksum
      script:
        - if [ -z $VERSION ]; then VERSION=$(echo $TRAVIS_COMMIT_MESSAGE | grep -oP "(?<=##)(.*)(?=##)"); fi
        - sudo bash scripts/ci/zip-files-checksum.sh $VERSION