language: node_js

image: docker

services:
  # docker:dind doesn't exist for travis ci
  - docker

# branches:
#   only:
#     - master
#     - master-schedule
#     - dev

before_install:
  - docker info
  - sudo apt-get update
  - sudo apt-get install bash grep
  - if [ -z $VERSION ]; then VERSION=$(echo $TRAVIS_COMMIT_MESSAGE | grep -oP "(?<=##)(.*)(?=##)"); fi
  - echo $VERSION

# if: branch = "master"
build-master:
  stage: build
  script:
    - docker version
    
    # -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY WRONG
    # - docker login -u DOCKER_USERNAME -p $DOCKER_PASSWORD $CI_REGISTRY
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker build -t $CI_REGISTRY_IMAGE:$VERSION .
    - docker push $CI_REGISTRY_IMAGE:$VERSION
    # - bundle exec rake
  only:
    - master
    - master-schedule
  
# if: branch = "dev"
build-dev:
  stage: build
  script:
    - docker version
    # - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker build -t $CI_REGISTRY_IMAGE:$VERSION-dev .
    - docker push $CI_REGISTRY_IMAGE:$VERSION-dev
  only:
    - dev
  except:
    - schedules


# eliminar isto depois
# - echo "TESTAR O MAKE"
script:
  - docker version
  # echoes
  - echo "INSIDE THE LAST SCRIPT, NOT INTENTIONAL!!!"
  - echo $DOCKER_USERNAME
  - echo $DOCKER_PASSWORD
  - CI_REGISTRY="docker.com"
  # -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY WRONG
  # foi adicionado o escape character aos caracteres especiais das env DOCKER_USERNAME e DOCKER_PASSWORD
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $CI_REGISTRY
  # previous CI_REGISTRY = TRAVIS_REPO_SLUG
  - echo $TRAVIS_REPO_SLUG
  - echo $DOCKER_HUB_SLUG
  - docker build -t $DOCKER_HUB_SLUG:$VERSION .
  # - docker push $DOCKER_HUB_SLUG:$VERSION
  # docker push de com o path diretamente
  - docker push testegithub/veruka-test:$VERSION
